Implementing notify for Incoming Calls
ConnectyCube/connectycube-flutter-call-kit pull request #129
Opened 2023-12-21 18:28 UTC by tungs0ul

This pull request introduces the ability to notify Flutter from iOS when there is an incoming call.

2023-12-22 10:31 UTC, TatankaConCube requested changes
the feature should be implemented for both supported platforms, for android it should work in the terminated state too

2024-01-05 15:31 UTC, TatankaConCube commented on android/src/main/kotlin/com/connectycube/flutter/connectycube_flutter_call_kit/ConnectycubeFCMReceiver.kt
> +        if (data["signal_type"] == "startCall") {
this statement check is redundant cause we did it before in line 37

2024-01-05 15:39 UTC, TatankaConCube commented on android/src/main/kotlin/com/connectycube/flutter/connectycube_flutter_call_kit/ConnectycubeFCMReceiver.kt
> +
could you please create the separate method/function (like 'notifyAboutIncomingCall' or something like this) in the `ConnectycubeFlutterCallKitPlugin.kt` similar to `saveCallState` and call it here. don't forget to delete unused imports

2024-01-06 15:49 UTC, tungs0ul commented
> @tungs0ul have you checked the new feature on your side for both platforms?

yup i have tested for both

2024-01-10 10:09 UTC, merged

2024-01-10 11:26 UTC, TatankaConCube commented
@tungs0ul just now version [2.6.0](https://pub.dev/packages/connectycube_flutter_call_kit/versions/2.6.0) with your changes was published, thank you for your contribution